name: Run Node.js File

on:
  push:
    branches: [ "main" ]  # Trigger on pushes to the "main" branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to the "main" branch

jobs:
  build:

    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - uses: actions/checkout@v3  # Check out the code
    - uses: actions/setup-node@v3  # Set up Node.js
      with:
        node-version: 16.x  # Choose a specific Node.js version
    - run: npm ci  # Install dependencies
    - run: node index.js  # Run the index.js file
