name: Run Node.js Project

on:
  push:
    branches: [ "main" ]  # Trigger on pushes to the "main" branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to the "main" branch

jobs:
  build:

    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - uses: actions/checkout@v3  # Check out the code
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm ci  # Install dependencies from package.json, handling potential caching

  test:  # Add a job for testing (optional)

    runs-on: ubuntu-latest  # Consider using the same environment for consistency

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x  # Maintain compatibility with build environment
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies (repeat for testing)
      run: npm ci
    - name: Run tests
      run: npm test  # Replace with your actual test command

  deploy:  # Add a job for deployment (optional)

    runs-on: ubuntu-latest  # Adjust environment as needed for deployment platform

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x  # Maintain compatibility
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies (repeat for deployment)
      run: npm ci
    - name: Build for deployment (if applicable)
      run: npm run build  # Replace with your build command
    - name: Deploy application
      # Use appropriate deployment commands based on your platform
